apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-api.fullname" . }}
spec:
  selector:
    app: {{ include "demo-api.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
